CREATE TABLE IF NOT EXISTS properties (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  address TEXT NOT NULL,
  state VARCHAR(100) NOT NULL,
  purchase_price DECIMAL(12,2) NOT NULL,
  purchase_date DATE,
  current_value DECIMAL(12,2) NOT NULL,
  monthly_rent DECIMAL(10,2) DEFAULT 0,
  monthly_expenses DECIMAL(10,2) DEFAULT 0,
  down_payment DECIMAL(12,2) DEFAULT 0,
  loan_amount DECIMAL(12,2) DEFAULT 0,
  interest_rate DECIMAL(5,2) DEFAULT 0,
  loan_term_years INTEGER DEFAULT 30,
  property_type VARCHAR(50) NOT NULL,
  status VARCHAR(50) DEFAULT 'analyzing',
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
